version: '2'
services:
  react_stuttgart:
    command: ["babel-node", "server.js"]
    env_file:
      - ../../.env
    environment:
      NODE_ENV: development
      PATH: /var/www/node_modules/.bin:${PATH}
    expose:
      - "9090"
    image: saronia/node:7.2.0.8 # To be refined... it throws some errors after all
    networks:
      - react_stuttgart_network
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ../../:/var/www
    working_dir: /var/www

# --------------------------------------------------------------------------
#  External network
# --------------------------------------------------------------------------
#
#  The external network is necessary so that we can connect our backend
#  services w/ our frontend services!
#
#  Create bridge network if it does not exist yet:
#  docker network create react_stuttgart_network
#
networks:
  react_stuttgart_network:
    external: true
