// flow-typed signature: 7baae94eb3b7c3c58e4ea6afc7613f18
// flow-typed version: <<STUB>>/@saronia/saronia-ui_v^0.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@saronia/saronia-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@saronia/saronia-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@saronia/saronia-ui/lib/assets/styles/colors' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/assets/styles/distances' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/assets/styles/fonts' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/assets/styles/global' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/assets/styles/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/components/Button' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/lib/stories/Button.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@saronia/saronia-ui/lib/assets/styles/colors.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/assets/styles/colors'>;
}
declare module '@saronia/saronia-ui/lib/assets/styles/distances.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/assets/styles/distances'>;
}
declare module '@saronia/saronia-ui/lib/assets/styles/fonts.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/assets/styles/fonts'>;
}
declare module '@saronia/saronia-ui/lib/assets/styles/global.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/assets/styles/global'>;
}
declare module '@saronia/saronia-ui/lib/assets/styles/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/assets/styles/index'>;
}
declare module '@saronia/saronia-ui/lib/components/Button.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/components/Button'>;
}
declare module '@saronia/saronia-ui/lib/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/index'>;
}
declare module '@saronia/saronia-ui/lib/stories/Button.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/lib/stories/Button.stories'>;
}
