// flow-typed signature: bc697703948655ff001d84a6c0892481
// flow-typed version: <<STUB>>/@saronia/saronia-ui_v^0.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@saronia/saronia-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@saronia/saronia-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@saronia/saronia-ui/build/assets/constants/animation' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/border' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/color' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/font' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/icon' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/assets/constants/space' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Button/Button' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Button/Button.spec' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Button/Button.stories' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Button/Buttons' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Button/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Dimmer/Dimmer' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Dimmer/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H1' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H2' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H3' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H4' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H5' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/H6' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Heading/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Icon/Icon' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Icon/Icon.spec' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Icon/Icon.stories' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Icon/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Label/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Label/Label' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Label/Label.stories' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/List/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/List/List' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/List/List.stories' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/List/ListItem' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Segment/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Segment/Segment' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Segment/Segment.spec' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Segment/Segment.stories' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/components/Segment/Segments' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/constants' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/index' {
  declare module.exports: any;
}

declare module '@saronia/saronia-ui/build/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@saronia/saronia-ui/build/assets/constants/animation.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/animation'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/border.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/border'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/color.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/color'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/font.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/font'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/icon.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/icon'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/index'>;
}
declare module '@saronia/saronia-ui/build/assets/constants/space.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/assets/constants/space'>;
}
declare module '@saronia/saronia-ui/build/components/Button/Button.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Button/Button'>;
}
declare module '@saronia/saronia-ui/build/components/Button/Button.spec.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Button/Button.spec'>;
}
declare module '@saronia/saronia-ui/build/components/Button/Button.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Button/Button.stories'>;
}
declare module '@saronia/saronia-ui/build/components/Button/Buttons.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Button/Buttons'>;
}
declare module '@saronia/saronia-ui/build/components/Button/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Button/index'>;
}
declare module '@saronia/saronia-ui/build/components/Dimmer/Dimmer.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Dimmer/Dimmer'>;
}
declare module '@saronia/saronia-ui/build/components/Dimmer/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Dimmer/index'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H1.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H1'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H2.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H2'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H3.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H3'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H4.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H4'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H5.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H5'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/H6.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/H6'>;
}
declare module '@saronia/saronia-ui/build/components/Heading/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Heading/index'>;
}
declare module '@saronia/saronia-ui/build/components/Icon/Icon.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Icon/Icon'>;
}
declare module '@saronia/saronia-ui/build/components/Icon/Icon.spec.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Icon/Icon.spec'>;
}
declare module '@saronia/saronia-ui/build/components/Icon/Icon.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Icon/Icon.stories'>;
}
declare module '@saronia/saronia-ui/build/components/Icon/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Icon/index'>;
}
declare module '@saronia/saronia-ui/build/components/Label/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Label/index'>;
}
declare module '@saronia/saronia-ui/build/components/Label/Label.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Label/Label'>;
}
declare module '@saronia/saronia-ui/build/components/Label/Label.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Label/Label.stories'>;
}
declare module '@saronia/saronia-ui/build/components/List/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/List/index'>;
}
declare module '@saronia/saronia-ui/build/components/List/List.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/List/List'>;
}
declare module '@saronia/saronia-ui/build/components/List/List.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/List/List.stories'>;
}
declare module '@saronia/saronia-ui/build/components/List/ListItem.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/List/ListItem'>;
}
declare module '@saronia/saronia-ui/build/components/Segment/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Segment/index'>;
}
declare module '@saronia/saronia-ui/build/components/Segment/Segment.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Segment/Segment'>;
}
declare module '@saronia/saronia-ui/build/components/Segment/Segment.spec.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Segment/Segment.spec'>;
}
declare module '@saronia/saronia-ui/build/components/Segment/Segment.stories.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Segment/Segment.stories'>;
}
declare module '@saronia/saronia-ui/build/components/Segment/Segments.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/components/Segment/Segments'>;
}
declare module '@saronia/saronia-ui/build/constants.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/constants'>;
}
declare module '@saronia/saronia-ui/build/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/index'>;
}
declare module '@saronia/saronia-ui/build/types/index.js' {
  declare module.exports: $Exports<'@saronia/saronia-ui/build/types/index'>;
}
