/* @flow */
const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST';
const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';

const SELECT_EVENT_REQUEST = 'SELECT_EVENT_REQUEST';
const SELECT_EVENT_SUCCESS = 'SELECT_EVENT_SUCCESS';
const SELECT_EVENT_FAILURE = 'SELECT_EVENT_FAILURE';

const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';

export {
  FETCH_EVENTS_REQUEST,
  FETCH_EVENTS_SUCCESS,
  FETCH_EVENTS_FAILURE,
  FETCH_PHOTOS_REQUEST,
  FETCH_PHOTOS_SUCCESS,
  FETCH_PHOTOS_FAILURE,
  SELECT_EVENT_REQUEST,
  SELECT_EVENT_SUCCESS,
  SELECT_EVENT_FAILURE,
  SHOW_MODAL,
  HIDE_MODAL,
};
