/* @flow */
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';

export const FETCH_SPEAKERS_SUCCESS = 'FETCH_SPEAKERS_SUCCESS';
export const FETCH_SPONSORS_SUCCESS = 'FETCH_SPONSORS_SUCCESS';
export const FETCH_TALKS_SUCCESS = 'FETCH_TALKS_SUCCESS';
export const FETCH_VENUES_SUCCESS = 'FETCH_VENUES_SUCCESS';

export const SELECT_EVENT_REQUEST = 'SELECT_EVENT_REQUEST';
export const SELECT_EVENT_SUCCESS = 'SELECT_EVENT_SUCCESS';
export const SELECT_EVENT_FAILURE = 'SELECT_EVENT_FAILURE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
