export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCEEDED = 'AUTH_USER_SUCCEEDED';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';

export const UNAUTH_USER = 'UNAUTH_USER';

export const ADD_TECHNOLOGY = 'ADD_TECHNOLOGY';
