// flow-typed signature: f5efc9d58edc049a8a115862dc64b0e0
// flow-typed version: <<STUB>>/contentful_v^3.8.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contentful'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contentful' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contentful/browser-dist/contentful' {
  declare module.exports: any;
}

declare module 'contentful/browser-dist/contentful.min' {
  declare module.exports: any;
}

declare module 'contentful/browser' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful' {
  declare module.exports: any;
}

declare module 'contentful/dist/create-contentful-api' {
  declare module.exports: any;
}

declare module 'contentful/dist/create-link-resolver' {
  declare module.exports: any;
}

declare module 'contentful/dist/entities/asset' {
  declare module.exports: any;
}

declare module 'contentful/dist/entities/content-type' {
  declare module.exports: any;
}

declare module 'contentful/dist/entities/entry' {
  declare module.exports: any;
}

declare module 'contentful/dist/entities/index' {
  declare module.exports: any;
}

declare module 'contentful/dist/entities/space' {
  declare module.exports: any;
}

declare module 'contentful/dist/mixins/link-getters' {
  declare module.exports: any;
}

declare module 'contentful/dist/mixins/stringify-safe' {
  declare module.exports: any;
}

declare module 'contentful/dist/paged-sync' {
  declare module.exports: any;
}

declare module 'contentful/tonic-example' {
  declare module.exports: any;
}

declare module 'contentful/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contentful/browser-dist/contentful.js' {
  declare module.exports: $Exports<'contentful/browser-dist/contentful'>;
}
declare module 'contentful/browser-dist/contentful.min.js' {
  declare module.exports: $Exports<'contentful/browser-dist/contentful.min'>;
}
declare module 'contentful/browser.js' {
  declare module.exports: $Exports<'contentful/browser'>;
}
declare module 'contentful/dist/contentful.js' {
  declare module.exports: $Exports<'contentful/dist/contentful'>;
}
declare module 'contentful/dist/create-contentful-api.js' {
  declare module.exports: $Exports<'contentful/dist/create-contentful-api'>;
}
declare module 'contentful/dist/create-link-resolver.js' {
  declare module.exports: $Exports<'contentful/dist/create-link-resolver'>;
}
declare module 'contentful/dist/entities/asset.js' {
  declare module.exports: $Exports<'contentful/dist/entities/asset'>;
}
declare module 'contentful/dist/entities/content-type.js' {
  declare module.exports: $Exports<'contentful/dist/entities/content-type'>;
}
declare module 'contentful/dist/entities/entry.js' {
  declare module.exports: $Exports<'contentful/dist/entities/entry'>;
}
declare module 'contentful/dist/entities/index.js' {
  declare module.exports: $Exports<'contentful/dist/entities/index'>;
}
declare module 'contentful/dist/entities/space.js' {
  declare module.exports: $Exports<'contentful/dist/entities/space'>;
}
declare module 'contentful/dist/mixins/link-getters.js' {
  declare module.exports: $Exports<'contentful/dist/mixins/link-getters'>;
}
declare module 'contentful/dist/mixins/stringify-safe.js' {
  declare module.exports: $Exports<'contentful/dist/mixins/stringify-safe'>;
}
declare module 'contentful/dist/paged-sync.js' {
  declare module.exports: $Exports<'contentful/dist/paged-sync'>;
}
declare module 'contentful/index' {
  declare module.exports: $Exports<'contentful'>;
}
declare module 'contentful/index.js' {
  declare module.exports: $Exports<'contentful'>;
}
declare module 'contentful/tonic-example.js' {
  declare module.exports: $Exports<'contentful/tonic-example'>;
}
declare module 'contentful/version.js' {
  declare module.exports: $Exports<'contentful/version'>;
}
