// flow-typed signature: a61f1037c53a67e451755584d0a641d3
// flow-typed version: <<STUB>>/meetup-api_vgithub:soosap/meetup-api#18195c1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meetup-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meetup-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meetup-api/examples/Dashboard' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/EventCommentsStream' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/firstEvent' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/getCities' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/getgroup' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/getgroups' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/getLocations' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/myevents' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/NodeJS-Argentina_OAUTH' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/NodeJS-Argentina_OAUTH2' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/NodeJS-Argentina' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/OpenEventsStream' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/PhotoStream' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/RSVPstream' {
  declare module.exports: any;
}

declare module 'meetup-api/examples/uploadPhoto' {
  declare module.exports: any;
}

declare module 'meetup-api/lib/meetup' {
  declare module.exports: any;
}

declare module 'meetup-api/lib/myUtils' {
  declare module.exports: any;
}

declare module 'meetup-api/test/testEndpoints' {
  declare module.exports: any;
}

declare module 'meetup-api/tonicExample' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meetup-api/examples/Dashboard.js' {
  declare module.exports: $Exports<'meetup-api/examples/Dashboard'>;
}
declare module 'meetup-api/examples/EventCommentsStream.js' {
  declare module.exports: $Exports<'meetup-api/examples/EventCommentsStream'>;
}
declare module 'meetup-api/examples/firstEvent.js' {
  declare module.exports: $Exports<'meetup-api/examples/firstEvent'>;
}
declare module 'meetup-api/examples/getCities.js' {
  declare module.exports: $Exports<'meetup-api/examples/getCities'>;
}
declare module 'meetup-api/examples/getgroup.js' {
  declare module.exports: $Exports<'meetup-api/examples/getgroup'>;
}
declare module 'meetup-api/examples/getgroups.js' {
  declare module.exports: $Exports<'meetup-api/examples/getgroups'>;
}
declare module 'meetup-api/examples/getLocations.js' {
  declare module.exports: $Exports<'meetup-api/examples/getLocations'>;
}
declare module 'meetup-api/examples/myevents.js' {
  declare module.exports: $Exports<'meetup-api/examples/myevents'>;
}
declare module 'meetup-api/examples/NodeJS-Argentina_OAUTH.js' {
  declare module.exports: $Exports<'meetup-api/examples/NodeJS-Argentina_OAUTH'>;
}
declare module 'meetup-api/examples/NodeJS-Argentina_OAUTH2.js' {
  declare module.exports: $Exports<'meetup-api/examples/NodeJS-Argentina_OAUTH2'>;
}
declare module 'meetup-api/examples/NodeJS-Argentina.js' {
  declare module.exports: $Exports<'meetup-api/examples/NodeJS-Argentina'>;
}
declare module 'meetup-api/examples/OpenEventsStream.js' {
  declare module.exports: $Exports<'meetup-api/examples/OpenEventsStream'>;
}
declare module 'meetup-api/examples/PhotoStream.js' {
  declare module.exports: $Exports<'meetup-api/examples/PhotoStream'>;
}
declare module 'meetup-api/examples/RSVPstream.js' {
  declare module.exports: $Exports<'meetup-api/examples/RSVPstream'>;
}
declare module 'meetup-api/examples/uploadPhoto.js' {
  declare module.exports: $Exports<'meetup-api/examples/uploadPhoto'>;
}
declare module 'meetup-api/index' {
  declare module.exports: $Exports<'meetup-api'>;
}
declare module 'meetup-api/index.js' {
  declare module.exports: $Exports<'meetup-api'>;
}
declare module 'meetup-api/lib/meetup.js' {
  declare module.exports: $Exports<'meetup-api/lib/meetup'>;
}
declare module 'meetup-api/lib/myUtils.js' {
  declare module.exports: $Exports<'meetup-api/lib/myUtils'>;
}
declare module 'meetup-api/test/testEndpoints.js' {
  declare module.exports: $Exports<'meetup-api/test/testEndpoints'>;
}
declare module 'meetup-api/tonicExample.js' {
  declare module.exports: $Exports<'meetup-api/tonicExample'>;
}
