// flow-typed signature: 7d6a51c6a383c0244ba9fa0b7c3db8c1
// flow-typed version: <<STUB>>/react-inlinesvg_v^0.6.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-inlinesvg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-inlinesvg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-inlinesvg/lib/index' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/lib/shouldComponentUpdate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-inlinesvg/lib/index.js' {
  declare module.exports: $Exports<'react-inlinesvg/lib/index'>;
}
declare module 'react-inlinesvg/lib/shouldComponentUpdate.js' {
  declare module.exports: $Exports<'react-inlinesvg/lib/shouldComponentUpdate'>;
}
