// flow-typed signature: 99a78f1e49d3bf97f2cb0741918cd411
// flow-typed version: <<STUB>>/redux-form-saga_v^0.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form-saga/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form-saga/lib/index.js' {
  declare module.exports: $Exports<'redux-form-saga/lib/index'>;
}
